# Generated by Django 3.0.6 on 2020-07-25 15:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PraiseMePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('put_date', models.DateTimeField(verbose_name='게시일')),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donatorPraiseAuthor', to='account.Donator', verbose_name='수여자')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiverPraiseMeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PrasieMeAuthorReceiver', to='account.Receiver', verbose_name='댓글 작성 수여자')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReceiverPraiseComment', to='praiseMeApp.PraiseMePost')),
            ],
        ),
        migrations.CreateModel(
            name='DonatorPraiseMeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PrasieMeAuthorDonator', to='account.Donator', verbose_name='댓글 작성 헌혈자')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DonatorPraiseComment', to='praiseMeApp.PraiseMePost')),
            ],
        ),
    ]
