# Generated by Django 3.0.6 on 2020-07-25 15:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiverComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='댓글 작성일')),
                ('body', models.TextField(verbose_name='댓글 내용')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiverCommentAuthor', to='account.Receiver', verbose_name='댓글을 남긴 수혈자')),
            ],
        ),
        migrations.CreateModel(
            name='HelpPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='게시일')),
                ('deadLine', models.DateField(verbose_name='마감일')),
                ('finished', models.BooleanField(default=False, verbose_name='마감 여부')),
                ('description', models.TextField(verbose_name='특이사항')),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='account.Receiver', verbose_name='수혈자')),
            ],
        ),
        migrations.CreateModel(
            name='DonatorComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='댓글 작성일')),
                ('body', models.TextField(verbose_name='댓글 내용')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donatorCommentAuthor', to='account.Donator', verbose_name='댓글을 남긴 헌혈자')),
            ],
        ),
    ]
